name: Scan

on:
  workflow_run:
    workflows: ["Build and Deploy"]
    types: [completed]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ghcr.io

      - name: Run Trivy scan on Docker image (direct scan without pull)
        uses: aquasecurity/trivy-action@v0.20.0  # Latest version of Trivy
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        with:
          image: ghcr.io/${{ github.repository }}/fastapi-app:latest
          format: 'table'  # Optional: Output format (can be 'json', 'table', or 'sarif')
          severity: 'HIGH, CRITICAL' # Optional: Filter based on severity (LOW, MEDIUM, HIGH, CRITICAL)

      - name: Previous workflow failed
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: |
          echo "Previous workflow failed" 
